### PR TITLE
feat: Implement support for PTR records

### PR DESCRIPTION
**Pull request by fust**
This PR adds support for PTR records through the `INFOBLOX_CREATE_PTR` environment variable.

### CODE REVIEW

**Comment by kuritka** [comment]
Hi @fust , thx a lot for your PR. Excellent! Please, run `make lint` and do changes to pass linters.

**Comment by fust** [comment]
@kuritka None of those errors are related to the changes in this MR so I don't really fancy fixing them in this MR.
If these unrelated linting errors are blocking to this PR I will consider it but I don't really feel like it's my responsibility tbh.

**Comment by fust** [comment]
I corrected the errors `make lint` threw at me.
The Makefile could use a bit of work so it works a bit more intuitively and supports Linux but I'll leave that as future improvements.

**Comment by kuritka** [comment]
oh I see @fust, makes sense. Will come back to you on the PR.

**Comment by kuritka** [comment]
@furst, please rebase

**Review by kuritka — APPROVED** [review]

**Pull request merged**
